# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-03 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_json', '0002_auto_20180503_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_json.Category'),
        ),
    ]
